### PR TITLE
Add dl option for best rating and most downloaded

### PR DESCRIPTION
**Pull request by xificurC**
--download takes 2 new options - best-rating and most-downloaded - that
do just what they say, i.e. select the result with best rating or most
downloads.

### CODE REVIEW

**Comment by xificurC** [comment]
Since the master repo doesn't seem to be really alive I'm checking if you are :) Let me know what do you think of the PR.

**Comment by fbarthelery** [comment]
Great ! I think it will be better to create a new method to print the subtitle you download, instead of reusing the `DisplaySubtitleSearchResults()` with a one element array. 
Also I think the `filename.encode('utf-8')` is necessary with python3, if you can verify that it still works.

I have no plans to take the maintenance of this project, but I'm using it regularly so I try to keep it working :smile:

**Comment by xificurC** [comment]
Hi, thanks for the feedback! I'm not sure how much maintenance is needed on the project but it doesn't have very high goals right :) Just download a few subs, not that many options or tricks, so I hope it will survive.

I'm not an expert on python so not sure what changed on the transition to python 3. I dropped the encode part because the filenames were appearing as `b'my-file.ext'` in the prints. The printing worked for me with a file I tested but it didn't have any specific characters, just standard ASCII ones. Should I try using some crazy filename?

Sure, I can write a new function to print the chosen subtitle.

**Comment by xificurC** [comment]
Made the print change, but not near my arch book right now so can't test yet. Will try to look into the unicode encoding as well.

**Comment by xificurC** [comment]
Hey,
I tried running this with a unicode [check mark character](http://www.fileformat.info/info/unicode/char/2713/index.htm) in the name of the video file and worked just fine. Is that enough of a test? If not let me know what would you consider sufficient. From what I can see right now I don't see any issues.

**Comment by fbarthelery** [comment]
LGTM thanks :+1:

**Comment by xificurC** [comment]
Thanks too :wink:

**Pull request merged**
